<?php get_header(); ?>
<main>
  <section class="wrap hero" id="jai"><div><h1>Meet <span class="gradient">JAI</span></h1><h2>AI agents that work together<br>to get real work done.</h2><p class="muted">Workflow-based Multi-Agent AI platform<br>for modern enterprises.</p><div class="actions"><a class="btn primary" href="#action">See JAI in Action&nbsp; →</a><a class="btn" href="#contact">Book a Demo</a></div><div class="trust">Trusted by forward-thinking teams<div class="logos">▦ Microsoft　aws　NVIDIA　△ Google Cloud</div></div></div><div class="screen"><div class="workflow"><div class="node big">JAI Orchestrator</div><div class="connector"></div><div><span class="node">Research Agent</span><span class="node">Data Agent</span><span class="node">Decision Agent</span></div><div class="connector"></div><div class="node big">Validation &amp; Review</div></div></div></section>
  <section class="section"><div class="wrap story"><div><h2>AI can answer.<br>Businesses need<br>AI that can <span class="gradient">act.</span></h2><p class="muted">Most AI tools stop at answers.<br>JAI goes further—understanding work, coordinating agents, using your systems, and delivering real outcomes.</p></div><div class="story-card"><div class="play" aria-label="Play founder story"></div></div></div></section>
  <section class="section center"><div class="wrap"><span class="eyebrow">Introducing JAI</span><h2>One Platform. Many Agents. <span class="gradient">Real Outcomes.</span></h2><p class="section-lead">JAI orchestrates specialized AI agents in workflows to complete complex business processes.</p><div class="flow"><div class="flow-card"><b>Input</b><p>Files, Data,<br>Requests, APIs</p></div><div class="flow-card"><b>JAI</b><p>Orchestrator</p></div><div class="flow-card"><b>AI Agents</b><p>Research · Data<br>Decision · Action</p></div><div class="flow-card"><b>Tools &amp; Systems</b><p>Databases · CRM<br>Enterprise apps</p></div><div class="flow-card"><b>Outcome</b><p>Reports, Actions,<br>Decisions</p></div></div></div></section>
  <section class="section center"><div class="wrap"><span class="eyebrow">How JAI works</span><h2>Workflow-native. Agent-powered. Human-aligned.</h2><div class="steps"><?php foreach (array('Understand'=>'JAI understands your goal, data, and context.','Plan'=>'It creates a plan and breaks work into tasks.','Orchestrate'=>'The right agents are assigned and executed.','Act'=>'Agents use tools and systems to get work done.','Verify'=>'Results are validated and delivered securely.') as $title=>$copy) : ?><div class="step"><div class="num"><?php static $i=0; echo ++$i; ?></div><b><?php echo esc_html($title); ?></b><p><?php echo esc_html($copy); ?></p></div><?php endforeach; ?></div></div></section>
  <section class="section center" id="action"><div class="wrap"><span class="eyebrow">JAI in action</span><h2>See JAI in Action<br><span class="gradient">Real workflows. Real results.</span></h2><div class="videos"><?php foreach (array('Customer Onboarding Workflow','Financial Analysis Agent Team','Automated Support Resolution') as $video) : ?><article class="video"><div class="video-thumb"><div class="play"></div></div><h3><?php echo esc_html($video); ?></h3><p>End-to-end intelligent automation, coordinated by specialized agents.</p></article><?php endforeach; ?></div></div></section>
  <section class="section center"><div class="wrap"><span class="eyebrow">Business value</span><h2>Built for impact. Measured in results.</h2><div class="values"><?php foreach (array('Automate Complex Work','Coordinate at Scale','Scale with Confidence','Govern with Control') as $value) : ?><div class="value-card"><div class="icon">◎</div><b><?php echo esc_html($value); ?></b><p>Reliable, secure, and enterprise-ready from day one.</p></div><?php endforeach; ?></div><br><span class="eyebrow">Use cases</span><h2>Purpose-built for every function.</h2><div class="cases"><?php foreach (array('Operations','Finance','Sales & RevOps','HR','Customer Support') as $case) : ?><div class="case"><b><?php echo esc_html($case); ?></b><p>Transform work with intelligent automation.</p></div><?php endforeach; ?></div></div></section>
  <section class="quote"><div class="wrap quote-grid"><h2>“<br>JAI transformed the way we work.<br>What used to take days now takes minutes—with better accuracy.</h2><div class="stat">70%<small>Faster process execution</small></div><div class="stat">60%<small>Reduction in manual effort</small></div><div class="stat">90%+<small>Accuracy in outcomes</small></div></div></section>
  <section class="section"><div class="wrap story"><div class="story-card"><div class="play"></div></div><div><span class="eyebrow">Our story</span><h2>We're builders.<br>Solvers. Partners.</h2><p class="muted">Diagonal Matrix was founded on a simple belief—AI should help people do meaningful work, not create more of it. JAI is our answer to that belief.</p><p><em>Jay Prakash</em><br><small class="muted">Founder &amp; CEO, Diagonal Matrix</small></p></div></div></section>
  <section class="cta" id="contact"><div class="wrap"><div><h2>See what JAI can do for your business.</h2><small>Book a personalized demo and explore the possibilities.</small></div><a class="btn" href="mailto:hello@diagonalmatrix.com">Book a JAI Demo　→</a></div></section>
</main>
<?php get_footer(); ?>
